'use strict';
const fs=require('fs');const path=require('path');const c=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','catalog.json'),'utf8'));
const ids=new Set(c.cards.map(x=>x.id));if(c.cards.length!==315)throw Error(`cards ${c.cards.length}`);if(ids.size!==315)throw Error('duplicate card ids');
for(const r of ['common','rare','ultra','legendary','mythic'])if(!c.cards.some(x=>x.rarity===r))throw Error(`missing rarity ${r}`);
if(c.cards.some(x=>x.type!=='spell'))throw Error('v4 combat cards must all be spells');
if(c.cards.filter(x=>x.cardClass==='gene').length<150)throw Error('not enough monster gene spells');
if(new Set(c.cards.filter(x=>x.cardClass==='gene').map(x=>x.geneStyle)).size<5)throw Error('gene spell styles not varied');
if(c.items.length<120)throw Error('not enough items');if(c.biomes.length!==5)throw Error('expected 5 biomes');if(c.bosses.length!==5)throw Error('expected 5 bosses');if(c.enemies.length<200)throw Error('expected 200 normal monsters');
if(Object.keys(c.difficulties).sort().join(',')!=='hard,hell,normal')throw Error('difficulty catalog mismatch');
if(c.biomes.some(b=>!Array.isArray(b.scenes)||b.scenes.length<5))throw Error('biome scenes missing');
if(c.items.some(i=>!i.art||!i.category))throw Error('item visual metadata missing');
if(c.starterPool.length!==8)throw Error('starter spell pool should be 8');
if(c.cards.filter(x=>x.archiveOnly||x.limited).length<25)throw Error('rerun archive pool too small');
if(c.monsterParty?.maxSlots!==6||c.monsterParty?.pointBudget!==10)throw Error('monster party rules mismatch');
if(c.spellDeck?.min!==8||c.spellDeck?.max!==12)throw Error('spell deck rules mismatch');
console.log(`CATALOG_OK cards=${c.cards.length} spells=${c.cards.length} gene=${c.cards.filter(x=>x.cardClass==='gene').length} items=${c.items.length} monsters=${c.enemies.length+c.bosses.length}`);
